"""Initial Migration

Revision ID: 47b9d0fb4591
Revises: 
Create Date: 2025-04-30 22:36:13.911580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b9d0fb4591'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('divisions_competition_id_fkey', 'divisions', type_='foreignkey')
    op.drop_column('divisions', 'competition_id')
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dob', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.add_column('divisions', sa.Column('competition_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('divisions_competition_id_fkey', 'divisions', 'competitors', ['competition_id'], ['id'])
    # ### end Alembic commands ###
